In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/eth_food_price.csv")
df.head()

,Country,Admin 1,Admin 2,Market Name,Commodity,Price Type,Price Date,Collection Frequency,Price,Unit,Currency,Data Source,Trend,Pewi,ALPS Phase,Data Type,Upper (95%) CI,Lower (95%) CI,Forecast Methodology
0,Ethiopia,Afar,ZONE2,Abaala,Barley,Retail,15/01/2020,Monthly,1000.0,100 KG,ETB,WFP,NaN,NaN,NaN,Aggregated,NaN,NaN,NaN
1,Ethiopia,Afar,ZONE2,Abaala,Barley,Retail,15/02/2020,Monthly,1000.0,100 KG,ETB,WFP,NaN,NaN,NaN,Aggregated,NaN,NaN,NaN
2,Ethiopia,Afar,ZONE2,Abaala,Barley,Retail,15/08/2023,Monthly,9000.0,100 KG,ETB,WFP,NaN,NaN,NaN,Aggregated,NaN,NaN,NaN
3,Ethiopia,Afar,ZONE2,Abaala,Butter (cow milk),Retail,15/01/2026,Monthly,1500.0,KG,ETB,WFP,NaN,NaN,NaN,Aggregated,NaN,NaN,NaN
4,Ethiopia,Afar,ZONE2,Abaala,Butter (goat milk),Retail,15/01/2026,Monthly,900.0,KG,ETB,WFP,NaN,NaN,NaN,Aggregated,NaN,NaN,NaN

In [3]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54873 entries, 0 to 54872
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Country               54873 non-null  object
 1   Admin 1               54873 non-null  object
 2   Admin 2               54873 non-null  object
 3   Market Name           54873 non-null  object
 4   Commodity             54873 non-null  object
 5   Price Type            54873 non-null  object
 6   Price Date            54873 non-null  object
 7   Collection Frequency  54873 non-null  object
 8   Price                 54873 non-null  float64
 9   Unit                  54873 non-null  object
 10  Currency              54873 non-null  object
 11  Data Source           54873 non-null  object
 12  Trend                 32815 non-null  float64
 13  Pewi                  33042 non-null  float64
 14  ALPS Phase            33042 non-null  object
 15  Data Type             54873 non-null  object
 16  Upper (95%) CI        5177 non-null   float64
 17  Lower (95%) CI        5177 non-null   float64
 18  Forecast Methodology  5177 non-null   object
dtypes: float64(5), object(14)
memory usage: 8.0+ MB

,Price,Trend,Pewi,Upper (95%) CI,Lower (95%) CI
count,54873.000000,32815.000000,33042.000000,5177.000000,5177.000000
mean,4949.092767,4406.148734,0.192900,9728.134706,7372.586804
std,10020.150177,7754.237711,1.302098,17470.824325,13650.302179
min,0.880000,0.807900,-5.240200,5.429800,0.000000
25%,90.000000,130.433600,-0.700625,151.067700,101.131100
50%,1600.000000,2045.833400,0.068800,5477.172900,4013.234100
75%,6000.000000,5500.000000,0.953000,10916.453100,8270.893600
max,270000.000000,102747.468800,9.112200,195050.515600,171788.703100

In [4]:
df.columns = [
    'country', 'region', 'sub_region', 'market',
    'commodity', 'price_type', 'date',
    'frequency', 'price', 'unit', 'currency',
    'data_source', 'trend', 'pewi', 'alps_phase',
    'data_type', 'upper_ci', 'lower_ci', 'forecast_method'
]

In [5]:
df = df[['country', 'region', 'market', 'commodity', 'price_type', 'date', 'price']]

In [6]:
df.head()

    country region  market           commodity price_type        date   price
0  Ethiopia   Afar  Abaala              Barley     Retail  15/01/2020  1000.0
1  Ethiopia   Afar  Abaala              Barley     Retail  15/02/2020  1000.0
2  Ethiopia   Afar  Abaala              Barley     Retail  15/08/2023  9000.0
3  Ethiopia   Afar  Abaala   Butter (cow milk)     Retail  15/01/2026  1500.0
4  Ethiopia   Afar  Abaala  Butter (goat milk)     Retail  15/01/2026   900.0

In [7]:
df = df[df["country"] == 'Ethiopia']
df = df[df['price_type'] == "Retail"]

In [9]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 54873 entries, 0 to 54872
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     54873 non-null  object
 1   region      54873 non-null  object
 2   market      54873 non-null  object
 3   commodity   54873 non-null  object
 4   price_type  54873 non-null  object
 5   date        54873 non-null  object
 6   price       54873 non-null  float64
dtypes: float64(1), object(6)
memory usage: 3.3+ MB

In [12]:
df['date'] = pd.to_datetime(df['date'])
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [15]:
df.isnull().sum()

country       0
region        0
market        0
commodity     0
price_type    0
date          0
price         0
dtype: int64

In [16]:
df = df.drop_duplicates()

In [18]:
df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month

In [23]:
df.describe()
df['commodity'].value_counts()

Maize (white)                  6178
Livestock (Goat)               3253
Livestock (Sheep)              3105
Wheat                          2535
Wheat (white)                  2275
                               ...
Maize                             2
Taro                              2
Wage (non-qualified labour)       1
Potatoes (Irish)                  1
Kocho                             1
Name: commodity, Length: 89, dtype: int64

In [24]:
df.to_csv("../data/processed/cleaned.csv", index=False)